### ISSUE TITLE
как это работает?

### ISSUE THREAD

**Issue by ceregapro1** [lyricsdev/sandbox-giveaway-notify#1]
после танцев с бубном у меня удалось запустить это, хотел узнать как вообще работает скрипт и что нужно будет делать если найдётся ключ, спасибо
![image](https://user-images.githubusercontent.com/61007438/191129293-86ad1954-54bd-434e-90f4-eceb306981b0.png)
как я понимаю, когда скрипт видит что кол-во ключей >0 - приходит сообщение в хукнутый канал дискорда о том что типо появился ключ перейди по ссылке и вступи в раздачу?

**Comment by lyricsdev** [comment]
Да все верно, но скрипт старый, не обновлял его на Гите, рбновленный работает у меня в дискорд сервере https://discord.gg/U78Un5vZ

**Comment by ceregapro1** [comment]
Ой бл, спасибо, буду ждать ключиков, очень уж хочется новый движок во всей красе опробовать.
